#:schema https://raw.githubusercontent.com/zakstucke/zetch/v0.0.10/py_rust/src/config/schema.json

ignore_files = [".gitignore"]

exclude = []

[engine]
custom_extensions = []

# Sync pkg versions in non templated files as a post task:
[[tasks.post]]
commands = ["./dev_scripts/pkg.sh update_versions"]

[context.static]
PY_VERSION = { value = "0.0.7" }
JS_VERSION = { value = "0.0.28" }
RUST_VERSION = { value = "0.0.39" }
PY_RUST_VERSION = { value = "0.0.3" }
JS_ALIASES = { value = '{ "@root": "./bitbazaar", "@scripts": "./scripts" }', coerce = "json" }

[context.env]
DEBUG = { default = true, coerce = "bool" }
OTLP_OO_ENDPOINT = { default = "http://localhost:5080/api/default/" }
OTLP_OO_AUTH = { default = "Basic ZGV2QGRldi5jb206cGFzcw==" }         # Not security issue! This is just base64('dev@dev.com:pass')

[context.cli]
ROOT_DIR = { commands = ["pwd"] }
