name: Setup Rust
description: "Installs latest stable rust, and sets up sscache for caching."
inputs:
  qa:
    description: "Whether things like cargo-hack need installing."
    required: false
    default: "false"
  test:
    description: "Whether things like nextest need installing."
    required: false
    default: "false"
runs:
  using: composite
  steps:
    - name: Install rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt, clippy
    - name: Run sccache-cache
      uses: mozilla-actions/sccache-action@v0.0.4
    - name: Set Rust caching env vars
      shell: bash
      run: |
        echo "SCCACHE_GHA_ENABLED=true" >> $GITHUB_ENV
        echo "RUSTC_WRAPPER=sccache" >> $GITHUB_ENV
    - name: Run sccache stat for check
      shell: bash
      run: ${SCCACHE_PATH} --show-stats
    - name: "Install cargo-hack, used for feature checking in pre-commit."
      if: ${{ inputs.qa == 'true' }}
      uses: taiki-e/install-action@cargo-hack
    - name: Install nextest
      if: ${{ inputs.test == 'true' }}
      uses: taiki-e/install-action@nextest
