name: install redis
description: "install redis without starting a server"
runs:
  using: composite
  steps:
    - uses: shogo82148/actions-setup-redis@v1
      with:
        redis-version: "latest"
        auto-start: false
