[dependencies]
chrono = '0.4'
colored = '2.0'
comfy-table = '7.1'
once_cell = '1.18'
regex = '1.10'
shlex = '1.2'
spez = '0.1'
tracing = '0.1'
tracing-appender = '0.2'
parking_lot = {version = '0.12', features = ['nightly', 'deadlock_detection', 'serde']}
time = {version = '0.3', features = ['local-offset']}
tracing-subscriber = {version = '0.3', features = ['fmt', 'std', 'time']}
clap = {version = '4.4', features = ['derive', 'string']}
# #[cfg(feature = 'opentelemetry')]
tracing-opentelemetry = {version = '0.22', optional = true}
opentelemetry = {version = '0.21', default-features = false, features = ['trace'], optional = true}
opentelemetry-otlp = {version = '0.14', features = ['reqwest-client', 'reqwest-rustls', 'http-proto', 'tls'], optional = true}
opentelemetry_sdk = {version = '0.21', features = ['rt-tokio'], optional = true}
tonic = {version = '0.9', optional = true}
# #[cfg(feature = 'pyo3')]
pyo3 = {version = '0.20', features = ['auto-initialize'], optional = true}
# #[cfg(feature = 'axum')]
axum = {version = '0.7', optional = true}
aide = {version = '0.13', features = ['axum'], optional = true}

[dev-dependencies]
rstest = '0.18.2'
serial_test = '2.0'
tempfile = '3.8'
tokio = '1.35'

[features]
opentelemetry = ['dep:tracing-opentelemetry', 'dep:opentelemetry', 'dep:opentelemetry-otlp', 'dep:opentelemetry_sdk', 'dep:tonic']
pyo3 = ['dep:pyo3']
axum = ['dep:axum', 'dep:aide']

[lib]
crate-type = ['lib']
name = 'bitbazaar'
path = 'bitbazaar/lib.rs'

[package]
description = 'An assortment of publicly available cross-language utilities useful to my projects.'
edition = '2021'
license = 'MIT'
name = 'bitbazaar'
readme = 'README.md'
version = '0.0.9'

[profile]

[profile.profiler]
debug = true
incremental = true
inherits = 'release'
strip = false

[profile.test]
inherits = 'release'
