[dependencies]
chrono = '0.4'
colored = '2.0'
comfy-table = '7.1'
once_cell = '1.18'
regex = '1.10'
shlex = '1.2'
spez = '0.1'
tracing = '0.1'
tracing-appender = '0.2'
deadpool-redis = {version = "0.14", features = ["rt_tokio_1"], optional = true}
redis = {version = "0.24", features = ["aio", "json"], default-features = false, optional = true}
sha1_smol = {version = '1.0', optional = true}
serde = {version = "1.0", features = ["derive"], optional = true}
serde_json = {version = "1.0", optional = true}
run_script = {version = "0.10", optional = true}

[dependencies.aide]
features = ['axum']
optional = true
version = '0.13'

[dependencies.axum]
optional = true
version = '0.7'

[dependencies.clap]
features = ['derive', 'string']
version = '4.4'

[dependencies.opentelemetry]
default-features = false
features = ['trace']
optional = true
version = '0.21'

[dependencies.opentelemetry-otlp]
features = ['reqwest-client', 'reqwest-rustls', 'http-proto', 'tls']
optional = true
version = '0.14'

[dependencies.opentelemetry_sdk]
features = ['rt-tokio']
optional = true
version = '0.21'

[dependencies.parking_lot]
features = ['nightly', 'deadlock_detection', 'serde']
version = '0.12'

[dependencies.pyo3]
features = ['auto-initialize']
optional = true
version = '0.20'

[dependencies.time]
features = ['local-offset']
version = '0.3'

[dependencies.tonic]
optional = true
version = '0.9'

[dependencies.tracing-opentelemetry]
optional = true
version = '0.22'

[dependencies.tracing-subscriber]
features = ['fmt', 'std', 'time']
version = '0.3'

[dev-dependencies]
homedir = '0.2.1'
portpicker = '0.1.1'
rstest = '0.18.2'
serial_test = '2.0'
tempfile = '3.8'
tokio = '1.35'

[dev-dependencies.uuid]
features = ['v4']
version = '1.6.1'

[features]
cli = ['dep:run_script']
redis = ['dep:deadpool-redis', 'dep:redis', 'dep:serde', 'dep:serde_json', 'dep:sha1_smol']
axum = ['dep:axum', 'dep:aide']
opentelemetry = ['dep:tracing-opentelemetry', 'dep:opentelemetry', 'dep:opentelemetry-otlp', 'dep:opentelemetry_sdk', 'dep:tonic']
pyo3 = ['dep:pyo3']

[lib]
crate-type = ['lib']
name = 'bitbazaar'
path = 'bitbazaar/lib.rs'

[package]
description = 'An assortment of publicly available cross-language utilities useful to my projects.'
edition = '2021'
license = 'MIT'
name = 'bitbazaar'
readme = 'README.md'
version = '0.0.14'

[profile]

[profile.profiler]
debug = true
incremental = true
inherits = 'release'
strip = false

[profile.test]
inherits = 'release'
