[dependencies]

[lib]
crate-type = ['lib']
name = 'bitbazaar'
path = 'bitbazaar/lib.rs'

[package]
description = 'An assortment of publicly available cross-language utilities useful to my projects.'
edition = '2021'
license = 'MIT'
name = 'bitbazaar'
readme = 'README.md'
version = '0.0.1'

[profile]

[profile.profiler]
debug = true
incremental = true
inherits = 'release'
strip = false

[profile.test]
inherits = 'release'
