[package]
name = "bitbazaar"
description = "An assortment of publicly available cross-language utilities useful to my projects."
version = "0.0.20"
edition = "2021"
readme = "README.md"
license = "MIT"

[lib]
name = "bitbazaar"
crate-type = ["lib"]
path = "bitbazaar/lib.rs"

# Add your dependencies here
[dependencies]
parking_lot = {version = "0.12", features = ["deadlock_detection", "serde"]}
tracing = "0.1"
error-stack = "0.4"
bitbazaar = {version = "0.0.20", features = [
]}
chrono = '0.4'
colored = '2.0'
comfy-table = '7.1'
once_cell = '1.18'
regex = '1.10'
shlex = '1.2'
tracing-appender = '0.2'

[dependencies.clap]
features = ['derive', 'string']
version = '4.4'

[dependencies.deadpool-redis]
features = ['rt_tokio_1']
optional = true
version = '0.14'

[dependencies.opentelemetry]
default-features = false
features = ['trace']
optional = true
version = '0.21'

[dependencies.opentelemetry-otlp]
features = ['reqwest-client', 'reqwest-rustls', 'http-proto', 'tls']
optional = true
version = '0.14'

[dependencies.opentelemetry_sdk]
features = ['rt-tokio']
optional = true
version = '0.21'

[dependencies.redis]
default-features = false
features = ['aio', 'json']
optional = true
version = '0.24'

[dependencies.run_script]
optional = true
version = '0.10'

[dependencies.serde]
features = ['derive']
optional = true
version = '1.0'

[dependencies.serde_json]
optional = true
version = '1.0'

[dependencies.sha1_smol]
optional = true
version = '1.0'

[dependencies.time]
features = ['local-offset']
version = '0.3'

[dependencies.tonic]
optional = true
version = '0.9'

[dependencies.tracing-opentelemetry]
optional = true
version = '0.22'

[dependencies.tracing-subscriber]
features = ['fmt', 'std', 'time']
version = '0.3'

[dev-dependencies]
homedir = '0.2.1'
portpicker = '0.1.1'
rstest = '0.18.2'
serial_test = '2.0'
tempfile = '3.8'
tokio = '1.35'

[dev-dependencies.uuid]
features = ['v4']
version = '1.6.1'

[features]
cli = ['dep:run_script']
opentelemetry = ['dep:tracing-opentelemetry', 'dep:opentelemetry', 'dep:opentelemetry-otlp', 'dep:opentelemetry_sdk', 'dep:tonic']
redis = ['dep:deadpool-redis', 'dep:redis', 'dep:serde', 'dep:serde_json', 'dep:sha1_smol']

[profile.profiler]
inherits = "release"  # Adds on top of the default release profile
incremental = true
debug = true
strip = false

# Modifying the test runtime (from release is just so much faster)
[profile.test]
inherits = "release"  # Adds on top of the default release profile
