[dependencies]
thiserror = "1.0"
colored = "2.0"
chrono = "0.4"
parking_lot = {version = "0.12.1", features = [
  "nightly",
  "deadlock_detection",
  "serde",
]}
once_cell = "1.18.0"
log = "0.4.20"
comfy-table = "7.1.0"
shlex = "1.2.0"
fern = "0.6.2"
spez = "0.1.2"
pyo3 = {version = "0.20.0", features = ["auto-initialize"], optional = true}

[dev-dependencies]
rstest = "0.18.2"

[features]
# When enabled, pyo3 related functionality, e.g. pyo3 error traits, are enabled.
pyo3 = ['dep:pyo3']

[lib]
crate-type = ['lib']
name = 'bitbazaar'
path = 'bitbazaar/lib.rs'

[package]
description = 'An assortment of publicly available cross-language utilities useful to my projects.'
edition = '2021'
license = 'MIT'
name = 'bitbazaar'
readme = 'README.md'
version = '0.0.1'

[profile]

[profile.profiler]
debug = true
incremental = true
inherits = 'release'
strip = false

[profile.test]
inherits = 'release'
