[dependencies]
chrono = '0.4'
colored = '2.0'
comfy-table = '7.1.0'
fern = '0.6.2'
log = '0.4.20'
once_cell = '1.18.0'
shlex = '1.2.0'
spez = '0.1.2'
thiserror = '1.0'

[dependencies.parking_lot]
features = ['nightly', 'deadlock_detection', 'serde']
version = '0.12.1'

[dependencies.pyo3]
features = ['auto-initialize']
optional = true
version = '0.20.0'

[dev-dependencies]
rstest = '0.18.2'

[features]
pyo3 = ['dep:pyo3']

[lib]
crate-type = ['lib']
name = 'bitbazaar'
path = 'bitbazaar/lib.rs'

[package]
description = 'An assortment of publicly available cross-language utilities useful to my projects.'
edition = '2021'
license = 'MIT'
name = 'bitbazaar'
readme = 'README.md'
version = '0.0.2'

[profile]

[profile.profiler]
debug = true
incremental = true
inherits = 'release'
strip = false

[profile.test]
inherits = 'release'
