[package]
name = "bitbazaar_rs"
version = "0.0.0"
edition = "2021"
readme = "README.md"
license = "MIT"
# This crate should only be released as a python package, so disable any rust side crates publishing:
publish = false

[lib]
name = "bitbazaar_rs"
crate-type = ["cdylib"]
path = "src/lib.rs"

[dependencies]
pyo3 = {version = "0.20.0", features = [
  # Tells pyo3 we want to build an extension module (skips linking against libpython.so)
  "extension-module",
]}

[profile.profiler]
inherits = "release"  # Adds on top of the default release profile
incremental = true
debug = true
strip = false

# Modifying the test runtime (from release is just so much faster)
[profile.test]
inherits = "release"  # Adds on top of the default release profile
